### ISSUE TITLE
new branch for Silex 2.0

### ISSUE THREAD

**Issue by sebastianblum** [romainneutron/Imagine-Silex-Service-Provider#2]
Hello!

I'm playing around with silex 2.0, but in your composer.json, you require silex ~1.0, so I can't use your imagine provider.

Can you please create a 2.0 branch and change the silex dependency to ~2.0@dev

thank you very much

**Comment by qkdreyer** [comment]
+1

**Comment by romainneutron** [comment]
Hello, I don't maintain this project anymore, if you're interested in taking over it, drop me an email
